<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!-- standalone ist optional, Standard-Wert ist "no" -->

<!DOCTYPE musiksammlung [
  <!-- Definition der einzelnen Elemente -->
  <!-- Synthax:
    <!ELEMENT elementname (texliche Inhalt ODER Kindelemente)>
  -->

  <!-- Festlegung der Anzahl von Kindelementen
    ? = 0 oder 1
    * = beliebig oft, auch 0 mal
    + = beliebig oft, mindestens 1 mal
      = genau 1 mal
  -->

  <!-- 
    Leere Elemente:
    <!ELEMENT elementname EMPTY>
  -->

  <!-- 
    textlicher Inhalt: (#PCDATA)
  -->

  <!ELEMENT musiksammlung (album+)>

  <!ELEMENT album (label, (interpret | gruppe), titel, lied*)>

  <!ELEMENT label (#PCDATA)>
  <!ELEMENT interpret (#PCDATA)>
  <!ELEMENT gruppe (#PCDATA)>
  <!ELEMENT titel (#PCDATA)>
  <!ELEMENT lied (#PCDATA)>
]>

<musiksammlung>

  <album typ="CD" spielzeit="33:03">
    <label>Mute Records Limited</label>
    <interpret>Moby</interpret>
    <titel>Play</titel>
    <lied>Honey</lied>
    <lied>Find my baby</lied>
    <lied>Porcelain</lied>
    <lied>Why does my heart feel so bad?</lied>
    <lied>South side</lied>
    <lied>Rushing</lied>
    <lied>Bodyrock</lied>
    <lied>Natural Blues</lied>
    <lied>Machete</lied>
  </album>

  <album typ="Vinyl" spielzeit="35:06">
    <label>Sony Music</label>
    <gruppe>a-ha</gruppe>
    <titel>Minor earth and major sky</titel>
    <lied>Minor earth and major sky</lied>
    <lied>Little black</lied>
    <lied>...</lied>
  </album>

  <album typ="MP3" spielzeit="54:48">
    <label>T-Summer Ltd.</label>
    <interpret>Mesh</interpret>
    <titel>Fragmente</titel>
    <lied>Trust on you</lied>
    <lied>My defender</lied>
    <lied>...</lied>
  </album>

</musiksammlung>